version: '3.8'
services:
  gateway:
    build: ./server/gateway
    ports:
      - "4000:4000"
  world:
    build: ./server/world
  zone:
    build: ./server/zone
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mmo
      POSTGRES_PASSWORD: mmo_pass
      POSTGRES_DB: mmo_db
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
